site_name: Telegram Updater
site_url: https://telegramupdater.github.io/Docs/

nav:
  - Home: "index.md"
  - Zero to hero: "ZeroToHero.md"
  - "Features Explained":
      - "Updater Class": "FeaturesExplained/UpdaterClass.md"
  - "Different Sdks":
      - "Console app": "DifferentSdks/Console.md"

theme: readthedocs
docs_dir: site
site_dir: docs
