name: Build docs

on: push
  
jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: mkdocs build
    
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
        
